#! /usr/bin/env ruby

require_relative 'mesa_script'

if ARGV.size == 0 or %w[-h --help].include?(ARGV[0])
  puts ''
  puts "inlist2mesascript help:"
  puts '-----------------------'
  puts "Only one command, which converts an inlist to a mesascript file:"
  puts ''
  puts 'inlist2mesascript SOURCE OUTPUT.rb'
  puts ''
  puts 'where SOURCE is your mesa inlist and OUTPUT is the name of the'
  puts "mesascript file to be produced. '.rb' will not be appended, though"
  puts "the resulting file will be a ruby/mesascript file."
  puts ''
elsif ARGV.size == 2
  source = ARGV[0]
  output = ARGV[1]

  Inlist.inlist_to_mesascript(source, output, false)
else
  raise "Expected two arguments (received #{ARGV.size}). Enter 'inlist2mesa -h' for help."
end
